site_name: OpenShift Multiboot System
site_description: Documentation for Dell PowerEdge R630 OpenShift Multiboot System
site_author: Bart van den Heuvel
copyright: "&copy; 2025 Bart van den Heuvel - Omnisack Sandbox Project"
repo_url: https://github.com/redhat/r630-iscsi-switchbot
theme:
  name: material
  logo: docs/assets/images/r630-iscsi-switchbot-new-logo.png
  favicon: docs/assets/images/r630-iscsi-switchbot-new-logo.png
  palette:
    primary: red
    accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  custom_dir: docs_mkdocs/docs/assets
  
extra_css:
  - docs/assets/css/custom.css

docs_dir: docs_mkdocs
nav:
  - Home: README.md
  - Implementation:
    - Multiboot: MULTIBOOT_IMPLEMENTATION.md
    - Netboot: NETBOOT_IMPLEMENTATION.md
    - Implementation Summary: IMPLEMENTATION_SUMMARY.md
  - Testing:
    - Test Plan: TEST_PLAN.md
    - Test Results: TEST_RESULTS.md
  - Documentation:
    - TrueNAS Authentication: docs/TRUENAS_AUTHENTICATION.md
    - Troubleshooting: docs/TROUBLESHOOTING.md
    - Admin Handoff: docs/ADMIN_HANDOFF.md
    - GitHub Actions: docs/GITHUB_ACTIONS_USAGE.md
    - OpenShift Values System: docs/OPENSHIFT_VALUES_SYSTEM.md
    - Deployment Tracking: docs/DEPLOYMENT_TRACKING.md
    - Secrets Management:
      - Secrets Provider System: docs/SECRETS_PROVIDER.md
      - HashiCorp Vault Integration: docs/VAULT_SECRETS_MANAGEMENT.md
    - Component Architecture: docs/COMPONENT_ARCHITECTURE.md
    - Storage:
      - S3 Storage Integration: docs/S3_STORAGE.md
      - MinIO Dual-Bucket Setup: docs/MINIO_DUAL_BUCKET_SETUP.md
      - iSCSI and OpenShift Integration: docs/ISCSI_OPENSHIFT_INTEGRATION.md
      - iSCSI Target Creation: docs/ISCSI_TARGET_CREATION.md
      - iSCSI Block Devices with OpenShift Agent: docs/TRUENAS_ISCSI_FINDING_BLOCK_DEVICES_USE_OCP_AGENT_BASED.md
    - Brand Assets Guidelines: https://github.com/redhat/r630-iscsi-switchbot/blob/master/frontend/public/brand-assets/BRAND-ASSET-GUIDELINES.md
    - Examples: 
      - TrueNAS Auth Examples: docs/examples/truenas_auth.json.example
  - Future Development:
    - Enhancement Plan: ENHANCEMENT_PLAN.md
  - Project Status:
    - Project Completion: PROJECT_COMPLETION.md
    - Final Report: FINAL_REPORT.md
    - Final Demo Plan: docs/FINAL_DEMO_PLAN.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html

plugins:
  - search
