name: Generate OpenShift ISOs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenShift version (e.g., 4.18)'
        required: true
        default: '4.18'
      rendezvous_ip:
        description: 'Rendezvous IP for OpenShift agent installer'
        required: true
        default: '192.168.2.230'
      truenas_ip:
        description: 'TrueNAS server IP'
        required: true
        default: '192.168.2.245'
      skip_upload:
        description: 'Skip uploading to TrueNAS (true/false)'
        required: false
        default: 'false'

jobs:
  generate-iso:
    name: Generate OpenShift Agent ISO
    runs-on: self-hosted  # Use x86_64 local runner
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip --quiet
          pip install requests pyyaml --quiet
          
      - name: Generate OpenShift ISO
        env:
          OPENSHIFT_PULL_SECRET: ${{ secrets.OPENSHIFT_PULL_SECRET }}
        run: |
          python scripts/generate_openshift_iso.py \
            --version ${{ github.event.inputs.version }} \
            --rendezvous-ip ${{ github.event.inputs.rendezvous_ip }} \
            ${{ github.event.inputs.skip_upload == 'true' && '--skip-upload' || '' }}
            
      - name: Upload ISO to TrueNAS
        if: ${{ github.event.inputs.skip_upload != 'true' }}
        env:
          TRUENAS_SSH_KEY: ${{ secrets.TRUENAS_SSH_KEY }}
          TRUENAS_KNOWN_HOSTS: ${{ secrets.TRUENAS_KNOWN_HOSTS }}
        run: |
          # Setup SSH for TrueNAS
          mkdir -p ~/.ssh
          echo "$TRUENAS_SSH_KEY" > ~/.ssh/truenas_key
          chmod 600 ~/.ssh/truenas_key
          echo "$TRUENAS_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          
          # Upload using SCP
          scp -i ~/.ssh/truenas_key \
            ./agent.x86_64.iso \
            root@${{ github.event.inputs.truenas_ip }}:/mnt/tank/openshift_isos/${{ github.event.inputs.version }}/agent.x86_64.iso
          
          echo "ISO uploaded to TrueNAS at http://${{ github.event.inputs.truenas_ip }}/openshift_isos/${{ github.event.inputs.version }}/agent.x86_64.iso"
          
      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openshift-${{ github.event.inputs.version }}-iso
          path: ./agent.x86_64.iso
          retention-days: 7
